export const FETCH_BOOK_LOADING = 'FETCH_BOOK_LOADING';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAIL = 'FETCH_BOOK_FAIL';
export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_LOADING';

export const SET_HEADER_SUB_TITLE = 'SET_HEADER_SUB_TITLE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_ORDER = 'ADD_ORDER';
export const UPDATE_MY_ADDRESS = 'UPDATE_MY_ADDRESS';

export const EMPTY_CART = 'EMPTY_CART';
